config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new #render the form
    @article = Article.new
  end

  def create #save the form data
    #@article = Article.new(title: "...", body: "...")
    @article = Article.new(article_params) #more secure than above with a hash

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="artist-form">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div class="artist-form">
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
  </div>

  <div class="artist-form">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
 <div class="title">
    <h1>Artists</h1>
    <h2>The Better Artist of all times</h2>
  </div>

  <ul class="artists">
    <% @articles.each do |article| %>
        <li>
          <%= link_to article.title, article %>
        </li>
    <% end %>
  </ul>

  <div class="new-artist">
    <%= link_to "New Artist", new_article_path %>
  </div>

app/views/articles/new.html.erb
<h1 class="t-new-artist">New Artist</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>